name: "web_app"
mode: "dev"
port: 8081
version: "v0.1.4"
start_time: "2024-11-16 00:00:00"
machine_id: 1


auth:
  jwt_expire: 8670
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "sql_demo"
  max_open: 200
  max_idle: 50
redis:
  host: 10.188.190.198
  port: 6379
  db: 0